# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j7xelte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j7xelte/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/08130000000000000000000000000000.tlbin:system/app/mcRegistry/08130000000000000000000000000000.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000019.tlbin:system/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffff000000000000000000000045.tlbin:system/app/mcRegistry/ffffffff000000000000000000000045.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/j7xelte/proprietary/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001e.tlbin \
    vendor/samsung/j7xelte/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/j7xelte/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/samsung/j7xelte/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh \
    vendor/samsung/j7xelte/proprietary/etc/bluetooth/av_performance.conf:system/etc/bluetooth/av_performance.conf \
    vendor/samsung/j7xelte/proprietary/etc/bluetooth/bt_did.conf:system/etc/bluetooth/bt_did.conf \
    vendor/samsung/j7xelte/proprietary/etc/bluetooth/bt_stack.conf:system/etc/bluetooth/bt_stack.conf \
    vendor/samsung/j7xelte/proprietary/etc/bluetooth/iop_bt.db:system/etc/bluetooth/iop_bt.db \
    vendor/samsung/j7xelte/proprietary/etc/bluetooth/iop_device_list.conf:system/etc/bluetooth/iop_device_list.conf \
    vendor/samsung/j7xelte/proprietary/etc/ca.pem:system/etc/ca.pem \
    vendor/samsung/j7xelte/proprietary/etc/plmn_delta.bin:system/etc/plmn_delta.bin \
    vendor/samsung/j7xelte/proprietary/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
    vendor/samsung/j7xelte/proprietary/etc/sec_s3nrn80_rfreg.bin:system/etc/sec_s3nrn80_rfreg.bin \
    vendor/samsung/j7xelte/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/j7xelte/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/j7xelte/proprietary/etc/wifi/bcmdhd_apsta.bin_3s:system/etc/wifi/bcmdhd_apsta.bin_3s \
    vendor/samsung/j7xelte/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/j7xelte/proprietary/etc/wifi/bcmdhd_mfg.bin_3s:system/etc/wifi/bcmdhd_mfg.bin_3s \
    vendor/samsung/j7xelte/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/j7xelte/proprietary/etc/wifi/bcmdhd_sta.bin_3s:system/etc/wifi/bcmdhd_sta.bin_3s \
    vendor/samsung/j7xelte/proprietary/etc/wifi/cred.conf:system/etc/wifi/cred.conf \
    vendor/samsung/j7xelte/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/j7xelte/proprietary/etc/wifi/nvram_mfg.txt_3s:system/etc/wifi/nvram_mfg.txt_3s \
    vendor/samsung/j7xelte/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/j7xelte/proprietary/etc/wifi/nvram_net.txt_3s:system/etc/wifi/nvram_net.txt_3s \
    vendor/samsung/j7xelte/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/j7xelte/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/samsung/j7xelte/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/j7xelte/proprietary/lib/hw/audio.primary.universal7870.so:system/lib/hw/audio.primary.universal7870.so \
    vendor/samsung/j7xelte/proprietary/lib/hw/camera.universal7870.so:system/lib/hw/camera.universal7870.so \
    vendor/samsung/j7xelte/proprietary/lib/hw/nfc_nci.universal7870.so:system/lib/hw/nfc_nci.universal7870.so \
    vendor/samsung/j7xelte/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/j7xelte/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/j7xelte/proprietary/lib/hw/sensors.universal7870.so:system/lib/hw/sensors.universal7870.so \
    vendor/samsung/j7xelte/proprietary/lib/lib_DNSe_NRSS_ver226.so:system/lib/lib_DNSe_NRSS_ver226.so \
    vendor/samsung/j7xelte/proprietary/lib/lib_SamsungRec_V05001.so:system/lib/lib_SamsungRec_V05001.so \
    vendor/samsung/j7xelte/proprietary/lib/lib_SoundAlive_SRC384_ver300.so:system/lib/lib_SoundAlive_SRC384_ver300.so \
    vendor/samsung/j7xelte/proprietary/lib/libSamsungAPVoiceEngine.so:system/lib/libSamsungAPVoiceEngine.so \
    vendor/samsung/j7xelte/proprietary/lib/libsamsungDiamondVoice.so:system/lib/libsamsungDiamondVoice.so \
    vendor/samsung/j7xelte/proprietary/lib/lib_soundaliveresampler.so:system/lib/lib_soundaliveresampler.so \
    vendor/samsung/j7xelte/proprietary/lib/lib_SoundBooster_ver610.so:system/lib/lib_SoundBooster_ver610.so \
    vendor/samsung/j7xelte/proprietary/lib/libaudio-ril.so:system/lib/libaudio-ril.so \
    vendor/samsung/j7xelte/proprietary/lib/libaudioroute.so:system/lib/libaudioroute.so \
    vendor/samsung/j7xelte/proprietary/lib/libcamera_metadata.so:system/lib/libcamera_metadata.so \
    vendor/samsung/j7xelte/proprietary/lib/libcodecdump.so:system/lib/libcodecdump.so \
    vendor/samsung/j7xelte/proprietary/lib/libcsc.so:system/lib/libcsc.so \
    vendor/samsung/j7xelte/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/j7xelte/proprietary/lib/libexynoscamera3.so:system/lib/libexynoscamera3.so \
    vendor/samsung/j7xelte/proprietary/lib/libexynosgscaler.so:system/lib/libexynosgscaler.so \
    vendor/samsung/j7xelte/proprietary/lib/libexynosscaler.so:system/lib/libexynosscaler.so \
    vendor/samsung/j7xelte/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
    vendor/samsung/j7xelte/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/j7xelte/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/j7xelte/proprietary/lib/libpreprocessing_nxp.so:system/lib/libpreprocessing_nxp.so \
    vendor/samsung/j7xelte/proprietary/lib/libSamsungPostProcess.so:system/lib/libSamsungPostProcess.so \
    vendor/samsung/j7xelte/proprietary/lib/libSamsungPostProcessConvertor.so:system/lib/libSamsungPostProcessConvertor.so \
    vendor/samsung/j7xelte/proprietary/lib/libSamsungPreProcess.so:system/lib/libSamsungPreProcess.so \
    vendor/samsung/j7xelte/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/j7xelte/proprietary/lib/libsamsungRecord_ns.so:system/lib/libsamsungRecord_ns.so \
    vendor/samsung/j7xelte/proprietary/lib/libsamsungSoundbooster_ext.so:system/lib/libsamsungSoundbooster_ext.so \
    vendor/samsung/j7xelte/proprietary/lib/libsamsungSoundbooster_pgb.so:system/lib/libsamsungSoundbooster_pgb.so \
    vendor/samsung/j7xelte/proprietary/lib/libsecaudioinfo.so:system/lib/libsecaudioinfo.so \
    vendor/samsung/j7xelte/proprietary/lib/libseccameracore.so:system/lib/libseccameracore.so \
    vendor/samsung/j7xelte/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/j7xelte/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/j7xelte/proprietary/lib/libstainkiller.so:system/lib/libstainkiller.so \
    vendor/samsung/j7xelte/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/samsung/j7xelte/proprietary/lib/libtinycompress.so:system/lib/libtinycompress.so \
    vendor/samsung/j7xelte/proprietary/lib/libuniplugin.so:system/lib/libuniplugin.so \
    vendor/samsung/j7xelte/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/j7xelte/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/j7xelte/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/j7xelte/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/j7xelte/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/j7xelte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/j7xelte/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/j7xelte/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/j7xelte/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/j7xelte/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/bcm43438A1_V0056.0256.hcd:system/vendor/firmware/bcm43438A1_V0056.0256.hcd \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/bcm4343A0_V0072.0270.hcd:system/vendor/firmware/bcm4343A0_V0072.0270.hcd \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/sec_s3nrn80_firmware.bin:system/vendor/firmware/sec_s3nrn80_firmware.bin \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/setfile_3l2.bin:system/vendor/firmware/setfile_3l2.bin \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/setfile_3p3.bin:system/vendor/firmware/setfile_3p3.bin \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/setfile_5e3.bin:system/vendor/firmware/setfile_5e3.bin \
    vendor/samsung/j7xelte/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/j7xelte/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/samsung/j7xelte/proprietary/vendor/lib/libLifevibes_lvverx.so:system/vendor/lib/libLifevibes_lvverx.so \
    vendor/samsung/j7xelte/proprietary/vendor/lib/libLifevibes_lvvetx.so:system/vendor/lib/libLifevibes_lvvetx.so \
    vendor/samsung/j7xelte/proprietary/vendor/lib/libMcClient.so:system/vendor/lib/libMcClient.so \
    vendor/samsung/j7xelte/proprietary/vendor/lib/libMcRegistry.so:system/vendor/lib/libMcRegistry.so \
    vendor/samsung/j7xelte/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/j7xelte/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

PRODUCT_COPY_FILES += \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/dict:system/usr/srec/en-US/dict \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/dnn:system/usr/srec/en-US/dnn \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/endpointer_model:system/usr/srec/en-US/endpointer_model \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/ep_portable_mean_stddev:system/usr/srec/en-US/ep_portable_mean_stddev \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/hmm_symbols:system/usr/srec/en-US/hmm_symbols \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/hmmlist:system/usr/srec/en-US/hmmlist \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/input_mean_std_dev:system/usr/srec/en-US/input_mean_std_dev \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/norm_fst:system/usr/srec/en-US/norm_fst \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/portable_lstm:system/usr/srec/en-US/portable_lstm \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/portable_meanstddev:system/usr/srec/en-US/portable_meanstddev \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/word_classifier:system/usr/srec/en-US/word_classifier \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/commands.abnf:system/usr/srec/en-US/commands.abnf \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/magic_mic.config:system/usr/srec/en-US/magic_mic.config \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/voice_actions.config:system/usr/srec/en-US/voice_actions.config \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/voice_actions_compiler.config:system/usr/srec/en-US/voice_actions_compiler.config \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/g2p.data:system/usr/srec/en-US/g2p.data \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/lstm_model.uint8.data:system/usr/srec/en-US/lstm_model.uint8.data \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/APP_NAME.fst:system/usr/srec/en-US/APP_NAME.fst \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/CLG.prewalk.fst:system/usr/srec/en-US/CLG.prewalk.fst \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/confirmation_bias.fst:system/usr/srec/en-US/confirmation_bias.fst \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/CONTACT_NAME.fst:system/usr/srec/en-US/CONTACT_NAME.fst \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/contacts_bias.fst:system/usr/srec/en-US/contacts_bias.fst \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/contacts_disambig.fst:system/usr/srec/en-US/contacts_disambig.fst \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/lexicon.U.fst:system/usr/srec/en-US/lexicon.U.fst \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/SONG_NAME.fst:system/usr/srec/en-US/SONG_NAME.fst \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/rescoring.fst.louds:system/usr/srec/en-US/rescoring.fst.louds \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/class_normalizer.mfar:system/usr/srec/en-US/class_normalizer.mfar \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/normalizer.mfar:system/usr/srec/en-US/normalizer.mfar \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/offensive_word_normalizer.mfar:system/usr/srec/en-US/offensive_word_normalizer.mfar \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/endpointer_model.mmap:system/usr/srec/en-US/endpointer_model.mmap \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/ep_portable_model.mmap:system/usr/srec/en-US/ep_portable_model.mmap \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/pumpkin.mmap:system/usr/srec/en-US/pumpkin.mmap \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/offline_action_data.pb:system/usr/srec/en-US/offline_action_data.pb \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/config.pumpkin:system/usr/srec/en-US/config.pumpkin \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/monastery_config.pumpkin:system/usr/srec/en-US/monastery_config.pumpkin \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/semantics.pumpkin:system/usr/srec/en-US/semantics.pumpkin \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/APP_NAME.syms:system/usr/srec/en-US/APP_NAME.syms \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/CONTACT_NAME.syms:system/usr/srec/en-US/CONTACT_NAME.syms \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/graphemes.syms:system/usr/srec/en-US/graphemes.syms \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/phonelist.syms:system/usr/srec/en-US/phonelist.syms \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/phonemes.syms:system/usr/srec/en-US/phonemes.syms \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/SONG_NAME.syms:system/usr/srec/en-US/SONG_NAME.syms \
    vendor/samsung/j7xelte/proprietary/usr/srec/en-US/wordlist.syms:system/usr/srec/en-US/wordlist.syms

PRODUCT_COPY_FILES += \
    vendor/samsung/j7xelte/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/j7xelte/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/j7xelte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/j7xelte/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/j7xelte/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so

PRODUCT_COPY_FILES += \
    vendor/samsung/j7xelte/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/j7xelte/proprietary/lib/libril.so:system/lib/libril.so

PRODUCT_COPY_FILES += \
    vendor/samsung/j7xelte/proprietary/lib/libion_exynos.so:system/lib/libion_exynos.so
